using System.Text.Json.Serialization;
using CohesiveRP.Common.Utils.BusinessObjects;

namespace CohesiveRP.Storage.DTOs.SkillChecks
{
    /// <summary>
    /// Must match the structure generated by the chatCompletionPreset tied to the Pathfinder chat characters skills check initiator.
    /// </summary>
    public class LLMPathfinderCharactersSkillChecksScene
    {
        [JsonSchemaRequired]
        [JsonPropertyName("listOfCharactersByName")]
        public string[] AllCharactersByName { get; set; }

        [JsonSchemaRequired]
        [JsonPropertyName("actions")]
        public LLMPathfinderCharactersSkillChecksActions[] Actions { get; set; }
    }
}
