namespace CohesiveRP.Storage.DataAccessLayer.SceneTracker.BusinessObjects
{
    public enum MappedFacialExpression
    {
        Admiration,
        Amusement,
        Anger,
        Annoyance,
        Arousal,//Desire
        Arrogant,
        Bored,
        Confusion,
        Crying,
        Curiosity,
        Disappointment,
        Disapproval,
        Disgust,
        Embarrassment,
        Excitement,
        Fear,
        Gratitude,
        Grief,
        Jealousy,
        Joy,
        Laughing,
        Nervoussness,
        Neutral,// Default, Unknown
        Pride,
        Realization,
        Relief,
        Remorse,
        Sadness,
        Serious,
        Shy,
        Sleepy,
        Surprised,
        Worried,
    }
}
