using System.Text.Json.Serialization;

namespace CohesiveRP.Core.LLMProviderProcessors.Pathfinder.SkillChecksInitiator.BusinessObjects
{
    /// <summary>
    /// Must match the structure generated by the chatCompletionPreset tied to the Pathfinder chat characters skills check initiator.
    /// </summary>
    public class LLMPathfinderCharactersSkillChecksScene
    {
        [JsonPropertyName("listOfCharactersByName")]
        public string[] AllCharactersByName { get; set; }

        [JsonPropertyName("actions")]
        public LLMPathfinderCharactersSkillChecksActions[] Actions { get; set; }
    }
}
