using System.Text.Json.Serialization;

namespace CohesiveRP.Core.LLMProviderProcessors.Pathfinder.SkillChecksInitiator.BusinessObjects
{
    /* Examples:
    * [
        {
        "characterName": "Linota",
        "actionCategory": "Performance",
        "reasoning": "Linota is attempting to project calm and control despite visible signs of agitation like trembling fingers and a betraying tail swish, masking her intense emotions under a composed facade."
        },
        {
        "characterName": "Linota",
        "actionCategory": "Charisma",
        "reasoning": "Linota is engaging in a persuasive and challenging dialogue, setting terms and gauging Edward's understanding, using her words to negotiate the intimacy of touching her horns."
        },
        {
        "characterName": "Linota",
        "actionCategory": "Sex",
        "reasoning": "The scene is charged with sexual tension; the discussion about touching sensitive horns, her hunger, and the implied physical intimacy afterward fall under sensuality and sexual context."
        },
        {
        "characterName": "Edward",
        "actionCategory": "Charisma",
        "reasoning": "Edward is responding to Linota's challenge with confident persuasion, asserting his capability to handle her intensity in a flirtatious, persuasive manner."
        }
    ]
    * */
    /// <summary>
    /// Must match the structure generated by the chatCompletionPreset tied to the Pathfinder chat characters skills check initiator.
    /// </summary>
    public class LLMPathfinderCharactersSkillChecksActions
    {
        [JsonPropertyName("characterName")]
        public string CharacterName { get; set; }

        [JsonPropertyName("actionCategory")]
        public string ActionCategory { get; set; }// TODO: enum?

        [JsonPropertyName("reasoning")]
        public string Reasoning { get; set; }
    }
}
